export const achievementsData = [
  {
    name: "First Echo",
    description:
      "Complete your first mining session, sending your inaugural resonance into the Lattice.",
    icon: "first-echo.png",
    category: "MINING",
    requirementType: "MINING_SESSIONS",
    miningSessionsRequired: 1,
    reward: 50,
    rarity: "COMMON",
    isActive: true,
  },
  {
    name: "Realm Wanderer",
    description:
      "Mine nodes in 5 different realms, exploring the vast Echo Lattice.",
    icon: "realm-wanderer.png",
    category: "EXPLORATION",
    requirementType: "UNIQUE_REALMS_MINED",
    uniqueRealmsRequired: 5,
    reward: 100,
    rarity: "COMMON",
    isActive: true,
  },
  {
    name: "Harmonic Initiate",
    description:
      "Reach level 5 through accumulated XP, attuning to the Lattice's basic rhythms.",
    icon: "harmonic-initiate.png",
    category: "PROGRESSION",
    requirementType: "PLAYER_LEVEL",
    playerLevelRequired: 5,
    reward: 200,
    rarity: "UNCOMMON",
    isActive: true,
  },
  {
    name: "Node Master",
    description:
      "Achieve mastery level 3 in any NodeType, becoming one with its mythic essence.",
    icon: "node-master.png",
    category: "MASTERY",
    requirementType: "MASTERY_LEVEL",
    masteryLevelRequired: 3,
    reward: 300,
    rarity: "RARE",
    isActive: true,
  },
  {
    name: "Phase Awakener",
    description:
      "Be the Pioneer whose mining session triggers a new Harmonic Awakening.",
    icon: "phase-awakener.png",
    category: "SPECIAL",
    requirementType: "PHASE_TRIGGERED",
    phaseTriggeredRequired: 1,
    reward: 1000,
    rarity: "LEGENDARY",
    isActive: true,
  },
  {
    name: "Collective Harmony",
    description: "Participate in a guild that contributes to a phase trigger.",
    icon: "collective-harmony.png",
    category: "SOCIAL",
    requirementType: "GUILD_PHASE_CONTRIBUTION",
    guildPhaseContributionRequired: 1,
    reward: 400,
    rarity: "RARE",
    isActive: true,
  },
  {
    name: "Lore Seeker",
    description:
      "Collect 10 lore fragments, unraveling the hidden myths of the Cosmos.",
    icon: "lore-seeker.png",
    category: "EXPLORATION",
    requirementType: "LORE_FRAGMENTS_COLLECTED",
    loreFragmentsCollectedRequired: 10,
    reward: 250,
    rarity: "UNCOMMON",
    isActive: true,
  },
  {
    name: "Infusion Adept",
    description: "Use 5 firmware boosts, mastering temporary cosmic surges.",
    icon: "infusion-adept.png",
    category: "PROGRESSION",
    requirementType: "BOOSTS_USED",
    boostsUsedRequired: 5,
    reward: 350,
    rarity: "RARE",
    isActive: true,
  },
  {
    name: "Legendary Harmonizer",
    description:
      "Mine a Legendary node, claiming the immortal vibration from the Lattice's core.",
    icon: "legendary-harmonizer.png",
    category: "MINING",
    requirementType: "MINED_NODE_RARITY",
    minedNodeRarityRequired: "LEGENDARY",
    reward: 500,
    rarity: "EPIC",
    isActive: true,
  },
  {
    name: "Surge Survivor",
    description: "Complete a session in a node with max concurrency.",
    icon: "surge-survivor.png",
    category: "MINING",
    requirementType: "MAX_CONCURRENCY_MINED",
    maxConcurrencyMinedRequired: 1,
    reward: 200,
    rarity: "RARE",
    isActive: true,
  },
  {
    name: "Bin Explorer",
    description: "Mine in 3 different geo-bins, expanding your echo reach.",
    icon: "bin-explorer.png",
    category: "EXPLORATION",
    requirementType: "UNIQUE_BINS_MINED",
    uniqueBinsMinedRequired: 3,
    reward: 150,
    rarity: "COMMON",
    isActive: true,
  },
  {
    name: "Echo Collector",
    description: "Accumulate 500 shares, ready for crystallization.",
    icon: "echo-collector.png",
    category: "PROGRESSION",
    requirementType: "SHARES_ACCUMULATED",
    sharesAccumulatedRequired: 500,
    reward: 100,
    rarity: "UNCOMMON",
    isActive: true,
  },
  {
    name: "Phase Participant",
    description: "Complete 10 sessions in a single phase.",
    icon: "phase-participant.png",
    category: "SPECIAL",
    requirementType: "SESSIONS_PER_PHASE",
    sessionsPerPhaseRequired: 10,
    reward: 300,
    rarity: "RARE",
    isActive: true,
  },
  {
    name: "Mini-Task Master",
    description: "Complete 20 mini-tasks during lock-ins.",
    icon: "mini-task-master.png",
    category: "MINING",
    requirementType: "MINI_TASKS_COMPLETED",
    miniTasksCompletedRequired: 20,
    reward: 250,
    rarity: "UNCOMMON",
    isActive: true,
  },
  {
    name: "Boost Virtuoso",
    description: "Use 10 different firmware boosts.",
    icon: "boost-virtuoso.png",
    category: "PROGRESSION",
    requirementType: "BOOSTS_TYPES_USED",
    boostsTypesUsedRequired: 10,
    reward: 400,
    rarity: "EPIC",
    isActive: true,
  },
  {
    name: "Social Resonator",
    description: "Invite 5 friends to the Realm.",
    icon: "social-resonator.png",
    category: "SOCIAL",
    requirementType: "FRIENDS_INVITED",
    friendsInvitedRequired: 5,
    reward: 200,
    rarity: "RARE",
    isActive: true,
  },
  {
    name: "Lattice Legend",
    description: "Reach level 20 and master 5 NodeTypes.",
    icon: "lattice-legend.png",
    category: "MASTERY",
    requirementType: "NODE_TYPES_MASTERED",
    playerLevelRequired: 20,
    nodeTypesMasteredRequired: 5,
    reward: 1000,
    rarity: "LEGENDARY",
    isActive: true,
  },
  {
    name: "Echo Hoarder",
    description: "Hold 10,000 shares without claiming.",
    icon: "echo-hoarder.png",
    category: "PROGRESSION",
    requirementType: "SHARES_HELD",
    sharesHeldRequired: 10000,
    reward: 500,
    rarity: "EPIC",
    isActive: true,
  },
  {
    name: "Awakening Witness",
    description: "Survive 3 Harmonic Awakenings.",
    icon: "awakening-witness.png",
    category: "SPECIAL",
    requirementType: "PHASES_SURVIVED",
    phasesSurvivedRequired: 3,
    reward: 600,
    rarity: "EPIC",
    isActive: true,
  },
  {
    name: "Realm Dominator",
    description: "Mine in a realm with 200% echo intensity.",
    icon: "realm-dominator.png",
    category: "EXPLORATION",
    requirementType: "ECHO_INTENSITY",
    echoIntensityRequired: 200,
    reward: 300,
    rarity: "RARE",
    isActive: true,
  },
  {
    name: "Myth Unraveler",
    description: "Collect all lore fragments for a phase.",
    icon: "myth-unraveler.png",
    category: "SPECIAL",
    requirementType: "LORE_FRAGMENTS_PER_PHASE",
    loreFragmentsPerPhaseRequired: "ALL",
    reward: 700,
    rarity: "LEGENDARY",
    isActive: true,
  },
] as const;
