// Rarity-dependent lore elements
export const commonAdjectives = [
  "Basic",
  "Simple",
  "Ordinary",
  "Everyday",
  "Plain",
  "Standard",
  "Commonplace",
  "Routine",
  "Mundane",
  "Typical",
];
export const uncommonAdjectives = [
  "Curious",
  "Unusual",
  "Intriguing",
  "Peculiar",
  "Odd",
  "Quirky",
  "Noteworthy",
  "Slightly Mysterious",
  "Faintly Glowing",
  "Subtly Resonant",
];
export const rareAdjectives = [
  "Ancient",
  "Forgotten",
  "Hidden",
  "Enigmatic",
  "Arcane",
  "Mystic",
  "Obscure",
  "Veiled",
  "Shadowed",
  "Whispering",
];
export const epicAdjectives = [
  "Powerful",
  "Majestic",
  "Grand",
  "Epic",
  "Heroic",
  "Legendary",
  "Glorious",
  "Radiant",
  "Thunderous",
  "Awe-Inspiring",
];
export const legendaryAdjectives = [
  "Cosmic",
  "Infinite",
  "Eternal",
  "Mythic",
  "Divine",
  "Transcendent",
  "Omniscient",
  "Primordial",
  "Celestial",
  "Godlike",
];

export const commonNouns = [
  "Point",
  "Spot",
  "Area",
  "Location",
  "Site",
  "Zone",
  "Field",
  "Patch",
  "Plot",
  "Ground",
];
export const uncommonNouns = [
  "Anomaly",
  "Outlier",
  "Curiosity",
  "Wonder",
  "Oddity",
  "Phenomenon",
  "Quirk",
  "Enigma",
  "Puzzle",
  "Riddle",
];
export const rareNouns = [
  "Relic",
  "Artifact",
  "Tome",
  "Scroll",
  "Rune",
  "Talisman",
  "Amulet",
  "Charm",
  "Sigil",
  "Glyph",
];
export const epicNouns = [
  "Bastion",
  "Fortress",
  "Citadel",
  "Stronghold",
  "Tower",
  "Pinnacle",
  "Summit",
  "Apex",
  "Zenith",
  "Crown",
];
export const legendaryNouns = [
  "Nexus",
  "Core",
  "Heart",
  "Essence",
  "Source",
  "Origin",
  "Fount",
  "Well",
  "Genesis",
  "Singularity",
];

export const commonEnvironments = [
  "plain field",
  "quiet meadow",
  "simple valley",
  "calm plain",
  "ordinary hill",
  "basic woodland",
  "routine path",
  "standard riverbank",
  "mundane clearing",
  "typical grove",
];
export const uncommonEnvironments = [
  "curious glade",
  "intriguing thicket",
  "peculiar canyon",
  "quirky stream",
  "noteworthy ridge",
  "faintly misty bog",
  "subtly shaded forest",
  "oddly shaped cliff",
  "slightly hidden cove",
  "unusually quiet lake",
];
export const rareEnvironments = [
  "ancient ruins",
  "forgotten cave",
  "hidden temple",
  "enigmatic labyrinth",
  "arcane grove",
  "mystic waterfall",
  "obscure mountain pass",
  "veiled oasis",
  "shadowed crypt",
  "whispering dune",
];
export const epicEnvironments = [
  "majestic peak",
  "grand canyon",
  "heroic battlefield",
  "glorious palace",
  "radiant volcano",
  "thunderous stormfront",
  "awe-inspiring abyss",
  "epic coliseum",
  "legendary forge",
  "pinnacle of clouds",
];
export const legendaryEnvironments = [
  "cosmic void",
  "infinite expanse",
  "eternal realm",
  "mythic heavens",
  "divine sanctuary",
  "transcendent plane",
  "omniscient oracle",
  "primordial chaos",
  "celestial throne",
  "godlike singularity",
];

export const commonLoreItems = [
  "basic shard",
  "simple crystal",
  "ordinary token",
  "everyday relic",
  "plain amulet",
  "standard scroll",
  "commonplace map",
  "routine essence",
  "mundane orb",
  "typical chalice",
];
export const uncommonLoreItems = [
  "curious fragment",
  "intriguing key",
  "peculiar stone",
  "quirky vial",
  "noteworthy pendant",
  "faintly glowing ring",
  "subtly enchanted coin",
  "oddly shaped idol",
  "slightly mysterious tome",
  "unusually warm gem",
];
export const rareLoreItems = [
  "ancient artifact",
  "forgotten dagger",
  "hidden scroll",
  "enigmatic talisman",
  "arcane rune",
  "mystic elixir",
  "obscure medallion",
  "veiled mask",
  "shadowed blade",
  "whispering staff",
];
export const epicLoreItems = [
  "powerful sword",
  "majestic crown",
  "grand shield",
  "heroic armor",
  "glorious banner",
  "radiant hammer",
  "thunderous bow",
  "awe-inspiring gauntlet",
  "epic helm",
  "legendary cloak",
];
export const legendaryLoreItems = [
  "cosmic scepter",
  "infinite orb",
  "eternal flame",
  "mythic star",
  "divine halo",
  "transcendent key",
  "omniscient eye",
  "primordial seed",
  "celestial wing",
  "godlike throne",
];
