import { v4 as uuidv4 } from "uuid";
import { NodeTypeRarity } from "../generated/prisma/enums";

// 20 NodeType instances across 10°x10° geo-bins, covering all rarities
export const nodeTypesData = [
  // Cell: 10N_20E (4 types)
  {
    id: uuidv4(),
    name: "10N_20E_Common",
    cellId: "10N_20E",
    description: "A faint hum of the Lattice pulses here.",
    extendedLore:
      "This common node resonates with the everyday echoes of Pioneers.",
    baseYieldPerMinute: 0.1,
    maxMiners: 50,
    lockInMinutes: 60,
    rarity: NodeTypeRarity.Common,
    iconUrl: "common-node.png",
    phase: 1,
    echoIntensity: 0.8,
  },
  {
    id: uuidv4(),
    name: "10N_20E_Uncommon",
    cellId: "10N_20E",
    description: "A steady rhythm vibrates through the Lattice.",
    extendedLore:
      "Uncommon energies converge, whispering secrets of the Cosmos.",
    baseYieldPerMinute: 0.2,
    maxMiners: 200,
    lockInMinutes: 120,
    rarity: NodeTypeRarity.Uncommon,
    iconUrl: "uncommon-node.png",
    phase: 1,
    echoIntensity: 0.9,
  },
  {
    id: uuidv4(),
    name: "10N_20E_Rare",
    cellId: "10N_20E",
    description: "A powerful surge courses through this node.",
    extendedLore: "Rare nodes channel the Lattice’s deeper harmonics.",
    baseYieldPerMinute: 0.5,
    maxMiners: 500,
    lockInMinutes: 360,
    rarity: NodeTypeRarity.Rare,
    iconUrl: "rare-node.png",
    phase: 1,
    echoIntensity: 1.1,
  },
  {
    id: uuidv4(),
    name: "10N_20E_Epic",
    cellId: "10N_20E",
    description: "A majestic pulse of cosmic energy.",
    extendedLore: "Epic nodes sing of ancient digits in the Lattice’s core.",
    baseYieldPerMinute: 0.8,
    maxMiners: 1000,
    lockInMinutes: 720,
    rarity: NodeTypeRarity.Epic,
    iconUrl: "epic-node.png",
    phase: 1,
    echoIntensity: 1.3,
  },
  // Cell: 0N_0E (4 types)
  {
    id: uuidv4(),
    name: "0N_0E_Common",
    cellId: "0N_0E",
    description: "A gentle echo of the Lattice’s birth.",
    extendedLore: "Common nodes here hum with primal resonance.",
    baseYieldPerMinute: 0.1,
    maxMiners: 50,
    lockInMinutes: 60,
    rarity: NodeTypeRarity.Common,
    iconUrl: "common-node.png",
    phase: 1,
    echoIntensity: 0.85,
  },
  {
    id: uuidv4(),
    name: "0N_0E_Uncommon",
    cellId: "0N_0E",
    description: "A vibrant chord in the cosmic symphony.",
    extendedLore: "Uncommon nodes pulse with shared dreams.",
    baseYieldPerMinute: 0.2,
    maxMiners: 200,
    lockInMinutes: 120,
    rarity: NodeTypeRarity.Uncommon,
    iconUrl: "uncommon-node.png",
    phase: 1,
    echoIntensity: 0.95,
  },
  {
    id: uuidv4(),
    name: "0N_0E_Rare",
    cellId: "0N_0E",
    description: "A rare harmonic vibrates strongly.",
    extendedLore: "These nodes echo forgotten cosmic battles.",
    baseYieldPerMinute: 0.5,
    maxMiners: 500,
    lockInMinutes: 360,
    rarity: NodeTypeRarity.Rare,
    iconUrl: "rare-node.png",
    phase: 1,
    echoIntensity: 1.15,
  },
  {
    id: uuidv4(),
    name: "0N_0E_Legendary",
    cellId: "0N_0E",
    description: "A cosmic roar of ancient digits.",
    extendedLore: "Legendary nodes guard the Lattice’s deepest truths.",
    baseYieldPerMinute: 1.0,
    maxMiners: 2000,
    lockInMinutes: 1440,
    rarity: NodeTypeRarity.Legendary,
    iconUrl: "legendary-node.png",
    phase: 1,
    echoIntensity: 1.5,
  },
  // Cell: 20N_30E (4 types)
  {
    id: uuidv4(),
    name: "20N_30E_Common",
    cellId: "20N_30E",
    description: "A soft pulse of the Lattice’s edge.",
    extendedLore: "Common nodes here whisper of distant stars.",
    baseYieldPerMinute: 0.1,
    maxMiners: 50,
    lockInMinutes: 60,
    rarity: NodeTypeRarity.Common,
    iconUrl: "common-node.png",
    phase: 1,
    echoIntensity: 0.82,
  },
  {
    id: uuidv4(),
    name: "20N_30E_Uncommon",
    cellId: "20N_30E",
    description: "A rising hum of cosmic intent.",
    extendedLore: "Uncommon nodes resonate with shared purpose.",
    baseYieldPerMinute: 0.2,
    maxMiners: 200,
    lockInMinutes: 120,
    rarity: NodeTypeRarity.Uncommon,
    iconUrl: "uncommon-node.png",
    phase: 1,
    echoIntensity: 0.92,
  },
  {
    id: uuidv4(),
    name: "20N_30E_Epic",
    cellId: "20N_30E",
    description: "An epic surge of Lattice energy.",
    extendedLore: "Epic nodes here chant of eternal cycles.",
    baseYieldPerMinute: 0.8,
    maxMiners: 1000,
    lockInMinutes: 720,
    rarity: NodeTypeRarity.Epic,
    iconUrl: "epic-node.png",
    phase: 1,
    echoIntensity: 1.35,
  },
  {
    id: uuidv4(),
    name: "20N_30E_Legendary",
    cellId: "20N_30E",
    description: "A legendary echo of the Cosmos.",
    extendedLore: "These nodes hold the Lattice’s ancient secrets.",
    baseYieldPerMinute: 1.0,
    maxMiners: 2000,
    lockInMinutes: 1440,
    rarity: NodeTypeRarity.Legendary,
    iconUrl: "legendary-node.png",
    phase: 1,
    echoIntensity: 1.45,
  },
  // Cell: 30N_40E (4 types)
  {
    id: uuidv4(),
    name: "30N_40E_Common",
    cellId: "30N_40E",
    description: "A quiet ripple in the Lattice.",
    extendedLore: "Common nodes pulse with humble energy.",
    baseYieldPerMinute: 0.1,
    maxMiners: 50,
    lockInMinutes: 60,
    rarity: NodeTypeRarity.Common,
    iconUrl: "common-node.png",
    phase: 1,
    echoIntensity: 0.81,
  },
  {
    id: uuidv4(),
    name: "30N_40E_Uncommon",
    cellId: "30N_40E",
    description: "A steady beat of cosmic resonance.",
    extendedLore: "Uncommon nodes sing of collective effort.",
    baseYieldPerMinute: 0.2,
    maxMiners: 200,
    lockInMinutes: 120,
    rarity: NodeTypeRarity.Uncommon,
    iconUrl: "uncommon-node.png",
    phase: 1,
    echoIntensity: 0.93,
  },
  {
    id: uuidv4(),
    name: "30N_40E_Rare",
    cellId: "30N_40E",
    description: "A rare pulse shakes the Lattice.",
    extendedLore: "Rare nodes echo with forgotten melodies.",
    baseYieldPerMinute: 0.5,
    maxMiners: 500,
    lockInMinutes: 360,
    rarity: NodeTypeRarity.Rare,
    iconUrl: "rare-node.png",
    phase: 1,
    echoIntensity: 1.12,
  },
  {
    id: uuidv4(),
    name: "30N_40E_Legendary",
    cellId: "30N_40E",
    description: "A legendary vibration of the Cosmos.",
    extendedLore: "Legendary nodes resonate with eternal truths.",
    baseYieldPerMinute: 1.0,
    maxMiners: 2000,
    lockInMinutes: 1440,
    rarity: NodeTypeRarity.Legendary,
    iconUrl: "legendary-node.png",
    phase: 1,
    echoIntensity: 1.48,
  },
  // Cell: 40N_50E (4 types)
  {
    id: uuidv4(),
    name: "40N_50E_Common",
    cellId: "40N_50E",
    description: "A soft echo of the Lattice’s song.",
    extendedLore: "Common nodes here hum with quiet power.",
    baseYieldPerMinute: 0.1,
    maxMiners: 50,
    lockInMinutes: 60,
    rarity: NodeTypeRarity.Common,
    iconUrl: "common-node.png",
    phase: 1,
    echoIntensity: 0.83,
  },
  {
    id: uuidv4(),
    name: "40N_50E_Uncommon",
    cellId: "40N_50E",
    description: "A growing pulse of cosmic harmony.",
    extendedLore: "Uncommon nodes vibrate with shared dreams.",
    baseYieldPerMinute: 0.2,
    maxMiners: 200,
    lockInMinutes: 120,
    rarity: NodeTypeRarity.Uncommon,
    iconUrl: "uncommon-node.png",
    phase: 1,
    echoIntensity: 0.94,
  },
  {
    id: uuidv4(),
    name: "40N_50E_Rare",
    cellId: "40N_50E",
    description: "A rare chord in the Lattice’s symphony.",
    extendedLore: "Rare nodes pulse with ancient energy.",
    baseYieldPerMinute: 0.5,
    maxMiners: 500,
    lockInMinutes: 360,
    rarity: NodeTypeRarity.Rare,
    iconUrl: "rare-node.png",
    phase: 1,
    echoIntensity: 1.14,
  },
  {
    id: uuidv4(),
    name: "40N_50E_Epic",
    cellId: "40N_50E",
    description: "An epic resonance of the Cosmos.",
    extendedLore: "Epic nodes sing of the Lattice’s heart.",
    baseYieldPerMinute: 0.8,
    maxMiners: 1000,
    lockInMinutes: 720,
    rarity: NodeTypeRarity.Epic,
    iconUrl: "epic-node.png",
    phase: 1,
    echoIntensity: 1.32,
  },
];

// 100 Node instances, distributed across the 5 cells, linked to node types
export const nodesData = Array.from({ length: 100 }, (_, index) => {
  const cellIds = ["10N_20E", "0N_0E", "20N_30E", "30N_40E", "40N_50E"];
  const cellId = cellIds[Math.floor(index / 20)]; // ~20 nodes per cell
  const typeIndex = index % 20; // Cycle through nodeTypesData
  const nodeType = nodeTypesData[typeIndex];
  const [latBase, lonBase] = cellId.split("_").map((s) => parseInt(s));
  const lat = latBase + Math.random() * 10;
  const lon = lonBase + Math.random() * 10;

  return {
    id: `node_${index + 1}_${uuidv4().slice(0, 8)}`,
    name: `Node ${index + 1} (${nodeType.rarity})`,
    typeId: nodeType.id,
    latitude: parseFloat(lat.toFixed(4)),
    longitude: parseFloat(lon.toFixed(4)),
    openForMining: true,
    sponsor: null,
    lore: `A pulsing ${nodeType.rarity.toLowerCase()} node at ${lat.toFixed(
      2
    )},${lon.toFixed(2)}.`,
    phase: 1,
    echoIntensity: nodeType.echoIntensity,
  };
});
