import { VaultUpgradeCreateInput } from "../generated/prisma/models";

export const vaultUpgrades: VaultUpgradeCreateInput[] = [
  {
    level: 1,
    name: "Initiate's Cache",
    description:
      "The foundation of a guild vault. Grants basic membership capacity and initial artifact storage.",
    resonanceCost: 0,
    // piCost: 0, // Field not in schema
    maxMembers: 20,
    artifactSlots: 1,
    sharePointsBonus: 0.0,
    prestigeBonus: 0.0,
    challengesUnlocked: false,
    territoryUnlocked: false,
    exclusiveCosmetics: false,
  },
  {
    level: 2,
    name: "Resonant Storage",
    description:
      "Expands the vault to allow for an additional artifact and slightly improved resource sharing.",
    resonanceCost: 500,
    // piCost: 0,
    maxMembers: 20,
    artifactSlots: 2,
    sharePointsBonus: 5.0,
    prestigeBonus: 0.0,
    challengesUnlocked: false,
    territoryUnlocked: false,
    exclusiveCosmetics: false,
  },
  {
    level: 3,
    name: "Challenger's Hold",
    description:
      "Unlocks Guild Challenges, allowing members to prove their worth and earn rewards.",
    resonanceCost: 1500,
    // piCost: 0,
    maxMembers: 20,
    artifactSlots: 2,
    sharePointsBonus: 8.0,
    prestigeBonus: 0.0,
    challengesUnlocked: true,
    territoryUnlocked: false,
    exclusiveCosmetics: false,
  },
  {
    level: 4,
    name: "Territorial Archive",
    description:
      "Unlocks the ability to stake claims on territories, expanding the guild's influence.",
    resonanceCost: 4000,
    // piCost: 2,
    maxMembers: 20,
    artifactSlots: 2,
    sharePointsBonus: 12.0,
    prestigeBonus: 0.0,
    challengesUnlocked: true,
    territoryUnlocked: true,
    exclusiveCosmetics: false,
  },
  {
    level: 5,
    name: "Expansion Chamber",
    description:
      "A significant structural upgrade that increases guild capacity to 30 members.",
    resonanceCost: 8000,
    // piCost: 5,
    maxMembers: 30,
    artifactSlots: 2,
    sharePointsBonus: 15.0,
    prestigeBonus: 0.0,
    challengesUnlocked: true,
    territoryUnlocked: true,
    exclusiveCosmetics: false,
  },
  {
    level: 6,
    name: "Artifact Reliquary",
    description:
      "Dedicated storage for high-power items. Increases artifact slots to 3.",
    resonanceCost: 15000,
    // piCost: 10,
    maxMembers: 30,
    artifactSlots: 3,
    sharePointsBonus: 18.0,
    prestigeBonus: 0.0,
    challengesUnlocked: true,
    territoryUnlocked: true,
    exclusiveCosmetics: false,
  },
  {
    level: 7,
    name: "Prestige Gallery",
    description:
      "Enhances the guild's reputation, providing a 1.5x multiplier (+50%) to prestige gains.",
    resonanceCost: 25000,
    // piCost: 20,
    maxMembers: 30,
    artifactSlots: 3,
    sharePointsBonus: 22.0,
    prestigeBonus: 50.0, // Represents 1.5x multiplier
    challengesUnlocked: true,
    territoryUnlocked: true,
    exclusiveCosmetics: false,
  },
  {
    level: 8,
    name: "Grand Assembly",
    description:
      "Maximum expansion of the main hall. Increases guild capacity to 40 members.",
    resonanceCost: 40000,
    // piCost: 35,
    maxMembers: 40,
    artifactSlots: 3,
    sharePointsBonus: 25.0,
    prestigeBonus: 50.0,
    challengesUnlocked: true,
    territoryUnlocked: true,
    exclusiveCosmetics: false,
  },
  {
    level: 9,
    name: "Opulent Sanctum",
    description:
      "A display of wealth that unlocks exclusive cosmetics for guild members.",
    resonanceCost: 60000,
    // piCost: 50,
    maxMembers: 40,
    artifactSlots: 3,
    sharePointsBonus: 30.0,
    prestigeBonus: 50.0,
    challengesUnlocked: true,
    territoryUnlocked: true,
    exclusiveCosmetics: true,
  },
  {
    level: 10,
    name: "Lattice Dominion",
    description:
      "The ultimate guild form. Max artifact slots, significant share bonuses, and the Dominion Guild Tag.",
    resonanceCost: 100000,
    // piCost: 100,
    maxMembers: 40,
    artifactSlots: 5,
    sharePointsBonus: 40.0,
    prestigeBonus: 50.0,
    challengesUnlocked: true,
    territoryUnlocked: true,
    exclusiveCosmetics: true,
  },
];
